### ISSUE TITLE
Support for Unity 2018.2.12f1? The windows target pkg installation fails sadly.

### ISSUE THREAD

**Issue by TheBlackPlague** [kevinta893/unity3d-travis-ci#1]
Any fixes? New to using Travis CI.

**Comment by kevinta893** [comment]
Could you post the build log from Travis here? That should give a clue as to what might be going on.

The main idea of this Travis CI enviroment is that it builds unity projects using the Mac OX version of Unity. From here, it is just a series of scripts (bash) to execute testing, building, and packaging your unity project.

As far as i know, using Unity in a CI enviroment like this for free is currently unsupported by the developers. So newer versions of unity may break it. You could try building with an older version. 

I would like to see if your issue could be a matter of an easy fix though. Otherwise, there's not much I can do as the Unity developers move towards supporting their Unity cloud build product.

**Comment by TheBlackPlague** [comment]
Log: https://hastebin.com/ebikimepok

**Comment by kevinta893** [comment]
Ah, so in the repository, there is a travis-build/install-unity.sh . In this script file are two instructions to install Unity itself, and a windows support plugin. 

From the logs, it seems that the package installer could not find the "UnitySetup-Windows-Support-for-Editor-2018.2.12f1.pkg" that it downloaded. I suggest inserting the `ls` command in the script to display the contents of the downloads folder and make sure that the file actually exists there and try again. It could be that the name of the file is wrong or the filepath is incorrect.

**Comment by TheBlackPlague** [comment]
@kevinta893 It seems more of an issue with the installer looking into the wrong path then the script. If anything we can do is just put the package in the appropriate file-path the installer is looking - as far as I believe. I do recommend you test yourself by creating a project and try building it with the same version. 

The Unity Installer is what I mean by the way.

^ This was understood from the 3rd last line of the error-log.

**Comment by kevinta893** [comment]
@TheBlackPlague . Sorry this took a while resolve. It is very difficult for me to debug the build since Travis does not currently support local debugging for their Mac OS enviroments. They don't have docker images available to test as far as I know.

Anyways your issue was with the download link provided to the Windows Build Support package. It was incorrectly generated in the script since Unity changed the way they named their links.

Anyways, I've updated the installation script to support 2018.2.12f1. Please see the [2018.2.12f1 branch](https://github.com/kevinta893/unity3d-travis-ci/tree/2018.2.12f1) and use the updated `install-unity.sh` script.

Please be aware that there is currently an issue with 2018.2.12f1. The Unity Package and Build scripts do not properly work and output a .unitypackage file to deploy on GitHub. This happens on the 2018.2.12f1 branch. I am currently investigating this when I find time.

Since this issue is only about the installation script, I will close this issue for now.

Thanks for your patience.
